//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cifrovizaciya.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        public int ID { get; set; }
        public int IDMeropriyatia { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public string Name { get; set; }
        public int IDModer { get; set; }
        public int IDGyri { get; set; }
        public int IDClients { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual gyri gyri { get; set; }
        public virtual Meropriaytie Meropriaytie { get; set; }
        public virtual Moder Moder { get; set; }
    }
}
