//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cifrovizaciya.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IgishevDemo2022Entities : DbContext
    {
        public IgishevDemo2022Entities()
            : base("name=IgishevDemo2022Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Activity> Activity { get; set; }
        public virtual DbSet<City> City { get; set; }
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<Country> Country { get; set; }
        public virtual DbSet<gyri> gyri { get; set; }
        public virtual DbSet<Meropriaytie> Meropriaytie { get; set; }
        public virtual DbSet<Moder> Moder { get; set; }
        public virtual DbSet<Napravlenie> Napravlenie { get; set; }
        public virtual DbSet<Organizatory> Organizatory { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
